---
# General configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config-map
  labels:
    app: pihole
data:
  PIHOLE_DNS_: 127.0.0.1#5053
  TZ: Asia/Manila
---
# Sensitive configurations
apiVersion: v1
kind: Secret
metadata:
  name: pihole-config-secret
  labels:
    app: pihole
data:
  WEBPASSWORD: '' # Modify
---
# Deployment specification
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/role
                  operator: In
                  values:
                    - master
      containers:
        # DNSCrypt
        - name: dnscrypt-proxy
          image: gists/dnscrypt-proxy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5353
              protocol: TCP
            - containerPort: 5353
              protocol: UDP
          volumeMounts:
            - name: dnscrypt
              mountPath: /etc/dnscrypt-proxy
          resources:
            limits:
              cpu: 250m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 50Mi
        # PiHole
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - name: dnsmasq
              mountPath: /etc/dnsmasq.d
            - name: etc
              mountPath: /etc/pihole
          livenessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 10
          envFrom:
            - configMapRef:
                name: pihole-config-map
            - secretRef:
                name: pihole-config-secret
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          resources:
            limits:
              cpu: 250m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 50Mi
      volumes:
        # DNSCrypt
        - name: dnscrypt
          hostPath:
            path: /mnt/containers/dnscrypt
        # PiHole
        - name: dnsmasq
          hostPath:
            path: /mnt/containers/pi-hole/dnsmasq.d
        - name: etc
          hostPath:
            path: /mnt/containers/pi-hole/pihole
---
# TCP Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: pihole-service-tcp
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: web
      protocol: TCP
      port: 8053
      targetPort: 80
    - name: dns
      protocol: TCP
      port: 53
---
# UDP Load Balancer
apiVersion: v1
kind: Service
metadata:
  name: pihole-service-udp
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: dns
      protocol: UDP
      port: 53
