apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: '${NFS_HOST}'
  share: ${NFS_SHARE}
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  # Maximum number of bytes of data that the NFS client can receive for each network READ request.
  - rsize=1048576
  # Maximum number of bytes of data that the NFS client can send for each network WRITE request.
  - wsize=1048576
  # Ensure data integrity
  - hard
  # Tells the NFS client to use a new Transmission Control Protocol (TCP) source port when a network connection is reestablished.
  - noresvport
  # NFS protocol version to negotiate
  - nfsvers=4.1
