{
 "title": "Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "omada_client_connected_total", "legendFormat": "Network" },
    { "expr": "pihole_unique_clients", "legendFormat": "DNS" },
    {
     "expr": "sum(count by(name) (container_start_time_seconds{name=~\".+\"}))",
     "legendFormat": "Container"
    },
    { "expr": "plex_sessions_active_count", "legendFormat": "Plex ({{server_name}})" }
   ]
  },
  {
   "title": "Services",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sort(sum by(job) (up))", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Torrents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrents{state!~\"moving|allocating|checking|total|downloading\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today", "legendFormat": "Total DNS queries" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Blocked DNS queries" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DNS queries",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pihole_dns_queries_today - pihole_ads_blocked_today",
     "legendFormat": "Allowed"
    },
    { "expr": "pihole_ads_blocked_today", "legendFormat": "Blocked" }
   ]
  },
  {
   "title": "Client download",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "omada_client_download_activity_bytes",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Node CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "omada_device_cpu_percentage", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Torrent bandwidth utilization",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(deluge_libtorrent_net_recv_bytes_total[1m])",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(deluge_libtorrent_net_sent_bytes_total[1m])",
     "legendFormat": "Upload"
    }
   ]
  },
  {
   "title": "Container CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m]) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Node memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "node_memory_Active_bytes / node_memory_MemTotal_bytes * 100",
     "legendFormat": "{{instance}}"
    },
    { "expr": "omada_device_mem_percentage", "legendFormat": "{{device}}" }
   ]
  }
 ]
}