apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-nfs-test-pvc
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-nfs-storage
  resources:
    requests:
      storage: 2Gi
