apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-smb-test-pvc
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: csi-smb-storage
  resources:
    requests:
      storage: 2Gi
