apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs-storage
provisioner: nfs.csi.k8s.io
parameters:
  server: '[NFS_HOST]'
  share: '[NFS_SHARE]'
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete  # available values: Delete, Retain
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1
