apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: synology-iscsi-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi.san.synology.com
parameters:
  dsm: '192.168.1.1'
  location: '/volume1'
  fsType: 'btrfs'
reclaimPolicy: Retain
allowVolumeExpansion: false
