########################################################################
# Extra variables:
# - None
# 
# Host inventory variables:
# - None
########################################################################
- name: Uninstall Recursive Domain Name System
  hosts: dns_server
  tasks:
    - name: Stop Docker containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      with_items:
        - pihole
        - unbound
        - wireguard

    - name: Remove Docker containers
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - pihole
        - unbound
        - wireguard
