########################################################################
# Extra variables:
# - ansible_host_ip (string)
# - ansible_user_gid (number)
# - ansible_user_uid (number) 
# 
# Host inventory variables:
# - None
########################################################################
- name: Install Recursive Domain Name System
  hosts: dns_server
  vars:
    network_cidr: 10.162.53.0/24
    pihole_home: /mnt/containers/pihole_recursive
    pihole_ip: 10.162.53.101
    pihole_port_dns: '53'
    pihole_port_web: '8053'
    unbound_home: /mnt/containers/unbound
    unbound_ip: 10.162.53.100
    wireguard_home: /mnt/containers/wireguard
    wireguard_ip: 10.162.53.102
    wireguard_port: '51820'
  tasks:
    - name: Create Docker network "dns_recursive_network"
      community.docker.docker_network:
        name: dns_recursive_network
        ipam_driver: default
        ipam_config:
          - subnet: "{{ network_cidr }}"

    - name: Start Unbound as a Docker container
      community.docker.docker_container:
        name: unbound
        image: mvance/unbound:latest
        container_default_behavior: no_defaults
        restart_policy: unless-stopped
        volumes:
          - "{{ unbound_home }}:/opt/unbound/etc/unbound/"
        networks_cli_compatible: yes
        network_mode: dns_recursive_network
        networks:
          - name: dns_recursive_network
            ipv4_address: "{{ unbound_ip }}"

    - name: Start Pi-hole as a Docker container
      community.docker.docker_container:
        name: pihole_recursive
        image: pihole/pihole:latest
        container_default_behavior: no_defaults
        restart_policy: unless-stopped
        ports:
          - "{{ ansible_host_ip }}:{{ pihole_port_web }}:80/TCP"
          - "{{ ansible_host_ip }}:{{ pihole_port_dns }}:53/TCP"
          - "{{ ansible_host_ip }}:{{ pihole_port_dns }}:53/UDP"
        volumes:
          - "{{ pihole_home }}/dnsmasq.d:/etc/dnsmasq.d"
          - "{{ pihole_home }}/pihole:/etc/pihole"
        env:
          # Never forward reverse lookups for private ranges
          DNS_BOGUS_PRIV: 'true' 
          # Never forward non-FQDNs
          DNS_FQDN_REQUIRED: 'true'
          # Upstream DNS server(s) for Pi-hole to forward queries to, seperated by a semicolon
          PIHOLE_DNS_: "{{ unbound_ip }}"
          # Set your timezone to make sure logs rotate at local midnight instead of at UTC midnight.
          TZ: Asia/Manila
          # No password. Change the password through:
          # docker exec -it pihole_recursive pihole -a -p
          WEBPASSWORD: ''
        capabilities:
          - NET_ADMIN
        networks_cli_compatible: yes
        network_mode: dns_recursive_network
        networks:
          - name: dns_recursive_network
            ipv4_address: "{{ pihole_ip }}"
