########################################################################
# Extra variables:
# - None
# 
# Host inventory variables:
# - None
########################################################################
- name: Uninstall DNS-over-HTTPS Domain Name System
  hosts: dns_server
  vars:
    container_names:
      - wireguard
      - pihole_doh
      - dnscrypt
  tasks:
    - name: Stop Docker containers
      community.docker.docker_container:
        name: "{{ item }}"
        container_default_behavior: no_defaults
        state: stopped
      with_items: "{{ container_names }}"
      failed_when: false

    - name: Remove Docker containers
      community.docker.docker_container:
        name: "{{ item }}"
        container_default_behavior: no_defaults
        state: absent
      with_items: "{{ container_names }}"
      failed_when: false
