########################################################################
# Extra variables:
# - ansible_host_ip (string)
# - ansible_user_gid (number)
# - ansible_user_uid (number) 
# 
# Host inventory variables:
# - None
########################################################################
- name: Install Recursive Domain Name System
  hosts: dns_server
  vars:
    network_cidr: 10.162.53.0/24
    pihole_home: /mnt/containers/pihole
    pihole_ip: 10.162.53.101
    pihole_port_dns: '53'
    pihole_port_web: '8053'
    unbound_home: /mnt/containers/unbound
    unbound_ip: 10.162.53.100
    wireguard_home: /mnt/containers/wireguard
    wireguard_ip: 10.162.53.102
    wireguard_port: '51820'
  tasks:
    - name: Create Docker network "dns_recursive_network"
      community.docker.docker_network:
        name: dns_recursive_network
        ipam_driver: default
        ipam_config:
          - subnet: "{{ network_cidr }}"

    - name: Start Unbound as a Docker container
      community.docker.docker_container:
        name: unbound
        image: mvance/unbound:latest
        container_default_behavior: no_defaults
        pull: true # Always pull the latest image
        restart_policy: unless-stopped
        volumes:
          - "{{ unbound_home }}/unbound.conf:/opt/unbound/etc/unbound/unbound.conf"
        networks_cli_compatible: yes
        network_mode: dns_recursive_network
        networks:
          - name: dns_recursive_network
            ipv4_address: "{{ unbound_ip }}"

    - name: Start Pi-hole as a Docker container
      community.docker.docker_container:
        name: pihole
        image: pihole/pihole:latest
        container_default_behavior: no_defaults
        pull: true # Always pull the latest image
        restart_policy: unless-stopped
        ports:
          - "{{ ansible_host_ip }}:{{ pihole_port_web }}:80/TCP"
          - "{{ ansible_host_ip }}:{{ pihole_port_dns }}:53/TCP"
          - "{{ ansible_host_ip }}:{{ pihole_port_dns }}:53/UDP"
        volumes:
          - "{{ pihole_home }}/dnsmasq.d:/etc/dnsmasq.d"
          - "{{ pihole_home }}/pihole:/etc/pihole"
        env:
          PIHOLE_DNS_: "{{ unbound_ip }}"
          ServerIP: "{{ pihole_ip }}"
          TZ: Asia/Manila
          WEBPASSWORD: ''
        capabilities:
          - NET_ADMIN
        dns_servers:
          - 127.0.0.1 # Points to localhost
          - "{{ unbound_ip }}"
        networks_cli_compatible: yes
        network_mode: dns_recursive_network
        networks:
          - name: dns_recursive_network
            ipv4_address: "{{ pihole_ip }}"

    - name: Start Wireguard as a Docker container
      community.docker.docker_container:
        name: wireguard
        image: linuxserver/wireguard:latest
        container_default_behavior: no_defaults
        pull: true # Always pull the latest image
        restart_policy: unless-stopped
        ports:
          - "{{ ansible_host_ip }}:{{ wireguard_port }}:51820/UDP"
        volumes:
          - "{{ wireguard_home }}:/config"
          - /var/modules:/lib/modules
        env:
          PEERDNS: "{{ pihole_ip }}"
          PEERS: mobile1,mobile2
          PUID: "{{ ansible_user_uid }}"
          PGID: "{{ ansible_user_gid }}"
          SERVERURL: "{{ ansible_host }}"
          SERVERPORT: "{{ wireguard_port }}"
          TZ: Asia/Manila
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        sysctls:
          net.ipv4.conf.all.src_valid_mark: 1
        dns_servers:
          - "{{ pihole_ip }}"
          - "{{ unbound_ip }}"
        networks_cli_compatible: yes
        network_mode: dns_recursive_network
        networks:
          - name: dns_recursive_network
            ipv4_address: "{{ wireguard_ip }}"
