########################################################################
# Extra variables:
# - None
# 
# Host inventory variables:
# - None
########################################################################
- name: Unmount Network Share
  hosts: dns_server
  vars:
    nfs_shares:
      - dst: /mnt/containers/dnscrypt
      - dst: /mnt/containers/pihole_doh
      - dst: /mnt/containers/pihole_recursive
      - dst: /mnt/containers/unbound
      - dst: /mnt/containers/wireguard
  tasks:
    - name: Unmount NFS share folders
      become: yes # Admin privileges required
      ansible.posix.mount:
        path: "{{ item.dst }}"
        state: unmounted
      with_items: "{{ nfs_shares }}"

    - name: Remove remnant folders
      become: yes # Admin privileges required
      ansible.builtin.file:
        path: "{{ item.dst }}"
        state: absent
      with_items: "{{ nfs_shares }}"
