---
# Certificate issuer
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: portainer-certificate-issuer
  namespace: portainer
  labels:
    app: portainer
spec:
  acme:
    email: '[ACME_OWNER_EMAIL]' # Modify
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: portainer-certificate-issuer-secret
    solvers: 
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            resourceGroupName: '[AZ_RES_GRP]' # Modify
            hostedZoneName: '[AZR_DOMAIN]' # Modify
            subscriptionID: '[AZ_SUB]' # Modify
            tenantID: '[AZ_SP_TENANT]' # Modify
            clientID: '[AZ_SP_CLIENT]' # Modify
            clientSecretSecretRef:
              name: acme-service-principal-secret
              key: CLIENT_SECRET
---
# Service ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portainer-ingress
  namespace: portainer
  labels:
    app: portainer
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/issuer: portainer-certificate-issuer
spec:
  tls:
    - secretName:  portainer-certificate-secret
      hosts:
        - portainer.[AZR_DOMAIN]
  rules:
    - host: portainer.[AZR_DOMAIN]
      http:
        paths:
          - pathType: Prefix 
            path: /
            backend:
              service:
                name: portainer-service-tcp
                port:
                  number: 9000
