version: '3'

################################################
# DEFINE SERVICES
################################################

services:

  # *** Unbound ***
  # Unbound is a validating, recursive, caching DNS resolver. It is designed to be fast and
  # lean and incorporates modern features based on open standards.

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    ports:
      - '127.0.0.1:5053:5353/tcp'
      - '127.0.0.1:5053:5353/udp'
    volumes:
      - '/export/containers/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro'
    restart: unless-stopped

  # *** Pi-hole ***
  # In addition to blocking advertisements, Pi-hole has an informative Web interface that
  # shows stats on all the domains being queried on your network.

  pihole:
    image: pihole/pihole:latest
    container_name: pihole-recursive
    ports:
      - '127.0.0.1:53:53/tcp'
      - '127.0.0.1:8053:80/tcp'
      - '127.0.0.1:53:53/udp'
    volumes:
      - '/export/containers/pihole/dnsmasq.d:/etc/dnsmasq.d'
      - '/export/containers/pihole/pihole:/etc/pihole'
    environment:
      PIHOLE_DNS_: '127.0.0.1#5053'
      TZ: 'Asia/Manila'
    restart: unless-stopped
    depends_on:
      - unbound
