version: '3'

################################################
# DEFINE SERVICES
#
# Environment variables:
# - DIR_UNBOUND (default: ./unbound)
# - DIR_PIHOLE (default: ./pihole)
# - HOST_IP (default: 127.0.0.1)
# - TIME_ZONE (default: Asia/Manila)
################################################

services:

  # *** Unbound ***
  # Unbound is a validating, recursive, caching DNS resolver. It is designed to
  # be fast and lean and incorporates modern features based on open standards.

  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    ports:
      - '${HOST_IP:-127.0.0.1}:5053:5353/tcp'
      - '${HOST_IP:-127.0.0.1}:5053:5353/udp'
    volumes:
      - ${DIR_UNBOUND:-./unbound}/unbound.conf:/opt/unbound/etc/unbound/unbound.conf:ro
    restart: unless-stopped

  # *** Pi-hole ***
  # In addition to blocking advertisements, Pi-hole has an informative Web interface that
  # shows stats on all the domains being queried on your network.

  pihole:
    image: pihole/pihole:latest
    container_name: pihole-recursive
    ports:
      - '${HOST_IP:-127.0.0.1}:53:53/tcp'
      - '${HOST_IP:-127.0.0.1}:53:53/udp'
      - '8053:80/tcp'
    volumes:
      - ${DIR_PIHOLE:-./pihole}/dnsmasq.d:/etc/dnsmasq.d
      - ${DIR_PIHOLE:-./pihole}/pihole:/etc/pihole
    environment:
      PIHOLE_DNS_: ${HOST_IP:-127.0.0.1}#5053
      TZ: ${TIME_ZONE:-Asia/Manila}
    restart: unless-stopped
    depends_on:
      - unbound
