version: '3'

################################################
# DEFINE SERVICES
#
# Environment Variables:
# - CAPTCHA_SOLVER (default: none)
# - DELUGE_PASS
# - DIR_DEEMIX (default: ./deemix)
# - DIR_DELUGE (default: ./deluge-vpn)
# - DIR_DOWNLOADS_ARR
# - DIR_DOWNLOADS_DEEMIX
# - DIR_DOWNLOADS_USENET
# - DIR_LIDARR (default: ./lidarr)
# - DIR_MEDIA
# - DIR_OVERSEERR (default: ./overseerr)
# - DIR_PROWLARR (default: ./prowlarr)
# - DIR_RADARR_FHD (default: ./radarr-fhd)
# - DIR_RADARR_UHD (default: ./radarr-uhd)
# - DIR_SABNZBD (default: ./sabnzbd-vpn)
# - DIR_SONARR_ANIME (default: ./sonarr-anime)
# - DIR_SONARR_TV (default: ./sonarr-tv)
# - HOST_CIDR (default: 192.168.1.0/24)
# - LOG_LEVEL (default: info)
# - LOG_HTML (default: false)
# - NAME_SERVERS (default: 192.168.1.1)
# - PUID (default: 1000)
# - PGID (default: 1000)
# - SABNZBD_API_KEY
# - TZ (default: Europe/London)
# - UMASK (default: 000)
# - VPN_CLIENT (default: wireguard)
# - VPN_INPUT_PORTS (default: no value)
# - VPN_OUTPUT_PORTS (default: no value)
# - VPN_PASS (default: no value)
# - VPN_PROV (default: custom)
# - VPN_USER (default: no value)
################################################
services:

  # *** Deluge VPN (custom image) ***
  # Deluge is a full-featured ​BitTorrent client for Linux, OS X, Unix and
  # Windows.

  # This Docker includes OpenVPN and WireGuard to ensure a secure and private
  # connection to the Internet, including use of iptables to prevent IP leakage
  # when the tunnel is down. It also includes Privoxy to allow unfiltered
  # access to index sites, to use Privoxy please point your application at
  # http://<host ip>:8118.

  deluge-vpn:
    image: binhex/arch-delugevpn:latest
    container_name: deluge-vpn
    volumes:
      - ${DIR_DELUGE:-./deluge-vpn}:/config
      - ${DIR_DOWNLOADS_ARR}:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.2
    environment:
      DEBUG: false # Options: true|false
      DELUGE_DAEMON_LOG_LEVEL: error # Options: info|warning|error|none|debug|trace|garbage
      DELUGE_WEB_LOG_LEVEL: error # Options: info|warning|error|none|debug|trace|garbage
      ENABLE_PRIVOXY: yes # Options: yes|no
      LAN_NETWORK: ${HOST_CIDR:-192.168.1.0/24}
      NAME_SERVERS: ${NAME_SERVERS:-192.168.1.1}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      STRICT_PORT_FORWARD: yes # Options: yes|no
      UMASK: ${UMASK:-000}
      VPN_ENABLED: yes # Options: yes|no
      VPN_USER: ${VPN_USER:-}
      VPN_PASS: ${VPN_PASS:-}
      VPN_PROV: ${VPN_PROV:-custom} # Options: pia|airvpn|custom
      VPN_CLIENT: ${VPN_CLIENT:-wireguard} # Options: openvpn|wireguard
      VPN_INPUT_PORTS: ${VPN_INPUT_PORTS:-}
      VPN_OUTPUT_PORTS: ${VPN_OUTPUT_PORTS:-}
    privileged: true
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped

  # *** SABnzbd ***
  # SABnzbd is an Open Source Binary Newsreader written in Python. It's totally
  # free, incredibly easy to use, and works practically everywhere. SABnzbd
  # makes Usenet as simple and streamlined as possible by automating everything
  # we can. All you have to do is add an .nzb.
  #
  # This Docker includes OpenVPN and WireGuard to ensure a secure and private
  # connection to the Internet, including use of iptables to prevent IP leakage
  # when the tunnel is down. It also includes Privoxy to allow unfiltered
  # access to index sites, to use Privoxy please point your application at
  # http://<host ip>:8118.

  sabnzbd-vpn:
    image: binhex/arch-sabnzbdvpn:latest
    container_name: sabnzbd-vpn
    volumes:
      - ${DIR_SABNZBD:-./sabnzbd-vpn}/logs:/config/logs
      - ${DIR_SABNZBD:-./sabnzbd-vpn}/wireguard:/config/wireguard
      - ${DIR_SABNZBD:-./sabnzbd-vpn}/sabnzbd.ini:/config/sabnzbd.ini
      - ${DIR_DOWNLOADS_USENET}:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.13
    environment:
      DEBUG: false # Options: true|false
      ENABLE_PRIVOXY: yes # Options: yes|no
      LAN_NETWORK: ${HOST_CIDR:-192.168.1.0/24}
      NAME_SERVERS: ${NAME_SERVERS:-192.168.1.1}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      STRICT_PORT_FORWARD: yes # Options: yes|no
      UMASK: ${UMASK:-000}
      VPN_ENABLED: yes # Options: yes|no
      VPN_USER: ${VPN_USER:-}
      VPN_PASS: ${VPN_PASS:-}
      VPN_PROV: ${VPN_PROV:-custom} # Options: pia|airvpn|custom
      VPN_CLIENT: ${VPN_CLIENT:-wireguard} # Options: openvpn|wireguard
      VPN_INPUT_PORTS: ${VPN_INPUT_PORTS:-}
      VPN_OUTPUT_PORTS: ${VPN_OUTPUT_PORTS:-}
    privileged: true
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped

  # *** Deemix ***
  # deemix (lowercase) is a barebone deezer downloader library built from the
  # ashes of Deezloader Remix

  deemix:
    image: registry.gitlab.com/bockiii/deemix-docker
    container_name: deemix
    volumes:
      - ${DIR_DEEMIX:-./deemix}:/config
      - ${DIR_DOWNLOADS_DEEMIX}:/downloads
    networks:
      internal_net:
        ipv4_address: 10.81.12.10
    environment:
      DEEMIX_SINGLE_USER: true
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      UMASK: ${UMASK:-022}

  # *** Lidarr ***
  # Lidarr is a music collection manager for Usenet and BitTorrent users.
  # It can monitor multiple RSS feeds for new tracks from your favorite
  # artists and will grab, sort and rename them. It can also be configured
  # to automatically upgrade the quality of files already downloaded when
  # a better quality format becomes available.

  # lidarr:
  #   image: binhex/arch-lidarr:latest
  #   container_name: lidarr
  #   volumes:
  #     - ${DIR_DOWNLOADS_ARR}:/data
  #     - ${DIR_MEDIA}:/media
  #     - ${DIR_LIDARR:-./lidarr}:/config
  #     - /etc/localtime:/etc/localtime:ro
  #   networks:
  #     internal_net:
  #       ipv4_address: 10.81.12.3
  #   environment:
  #     UMASK: ${UMASK:-000}
  #     PUID: ${PUID:-1000}
  #     PGID: ${PGID:-1000}
  #   restart: unless-stopped
  #   depends_on:
  #     - deluge-vpn
  #     - deemix

  # *** Radarr ***
  # This fork of Sonarr aims to turn it into something like Couchpotato.

  radarr_fhd:
    image: binhex/arch-radarr:latest
    container_name: radarr-fhd
    volumes:
      - ${DIR_DOWNLOADS_ARR}:/data
      - ${DIR_MEDIA}:/media
      - ${DIR_RADARR_FHD:-./radarr-fhd}:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.4
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  radarr_uhd:
    image: binhex/arch-radarr:latest
    container_name: radarr-uhd
    volumes:
      - ${DIR_DOWNLOADS_ARR}:/data
      - ${DIR_MEDIA}:/media
      - ${DIR_RADARR_UHD:-./radarr-uhd}:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.5
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  # *** Sonarr ***
  # Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple
  # RSS feeds for new episodes of your favorite shows and will grab, sort and
  # rename them. It can also be configured to automatically upgrade the quality
  # of files already downloaded when a better quality format becomes available.

  # sonarr_anime:
  #  image: binhex/arch-sonarr:latest
  #  container_name: sonarr-anime
  #  volumes:
  #    - ${DIR_DOWNLOADS_ARR}:/data
  #    - ${DIR_MEDIA}:/media
  #    - ${DIR_SONARR_ANIME:-./sonarr-anime}:/config
  #    - /etc/localtime:/etc/localtime:ro
  #  networks:
  #    internal_net:
  #      ipv4_address: 10.81.12.6
  #  environment:
  #    UMASK: ${UMASK:-000}
  #    PUID: ${PUID:-1000}
  #    PGID: ${PGID:-1000}
  #  restart: unless-stopped
  #  depends_on:
  #    - deluge-vpn

  sonarr_tv:
    image: binhex/arch-sonarr:latest
    container_name: sonarr-tv
    volumes:
      - ${DIR_DOWNLOADS_ARR}:/data
      - ${DIR_MEDIA}:/media
      - ${DIR_SONARR_TV:-./sonarr-tv}:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.7
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  # *** Overseerr ***
  # Overseerr is a request management and media discovery tool built to work
  # with your existing Plex ecosystem. Overseerr helps you find media you want
  # to watch. With inline recommendations and suggestions, you will find
  # yourself deeper and deeper in a rabbit hole of content you never knew you
  # just had to have.

  overseerr:
    image: binhex/arch-overseerr:latest
    container_name: overseerr
    volumes:
      - ${DIR_OVERSEERR:-./overseerr}:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.11
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      # - lidarr
      # - sonarr_anime
      - sonarr_tv
      - radarr_fhd
      - radarr_uhd

  # *** FlareSolverr ***
  # FlareSolverr is a proxy server to bypass Cloudflare and DDoS-GUARD
  # protection.

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    networks:
      internal_net:
        ipv4_address: 10.81.12.12
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
      TZ: ${TZ:-Europe/London}
    restart: unless-stopped

  # *** Prometheus Exporter ***
  # A Prometheus exporter for Deluge.

  deluge-monitor:
    image: tobbez/deluge_exporter:latest
    container_name: deluge-monitor
    volumes:
      - ${DIR_DELUGE:-./deluge-vpn}:/root/.config/deluge/:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.9
    environment:
      DELUGE_HOST: 10.81.12.2
      DELUGE_PASSWORD: ${DELUGE_PASS}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  # A Prometheus exporter for SABNzbd.

  sabnzbd-monitor:
    image: msroest/sabnzbd_exporter:latest
    container_name: sabnzbd-monitor
    networks:
      internal_net:
        ipv4_address: 10.81.12.14
    environment:
      SABNZBD_BASEURLS: http://10.81.12.13:8080
      SABNZBD_APIKEYS: ${SABNZBD_API_KEY}
    restart: unless-stopped
    depends_on:
      - sabnzbd-vpn

  # *** Prowlarr ***
  # Prowlarr is a indexer manager/proxy built on the popular arr .net/reactjs
  # base stack to integrate with your various PVR apps. Prowlarr supports both
  # Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr,
  # Radarr, Lidarr, and Readarr offering complete management of your indexers
  # with no per app Indexer setup required (we do it all).

  prowlarr:
    image: binhex/arch-prowlarr:latest
    container_name: prowlarr
    volumes:
      - ${DIR_PROWLARR:-./prowlarr}:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.81.12.8
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      # - lidarr
      # - sonarr_anime
      - sonarr_tv
      - radarr_fhd
      - radarr_uhd
  
################################################
# DEFINE NETWORKS
################################################
networks:

  # *** Internal network ***
  internal_net:
    name: download-manager-vlan
    driver: bridge
    ipam:
      config:
        - subnet: 10.81.12.0/24
          gateway: 10.81.12.1
