###############################################################################
# General IP address pool for MetalLB
#
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: general-pool
  namespace: metallb-system
spec:
  addresses:
    - ${METALLB_DEDICATED_CIDR}
  avoidBuggyIPs: true
###############################################################################
# Core IP address pool for MetalLB
#
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: core-pool
  namespace: metallb-system
spec:
  addresses:
    - ${METALLB_CORE_CIDR}
  avoidBuggyIPs: true
  autoAssign: false
