########################################################################
# Extra variables:
# - k3s_fixed_reg_addr (string)
#
# Host inventory variables:
# - ansible_user (builtin)
########################################################################
- name: Install k3s to local worker nodes
  hosts: k8s_workers_local
  tasks:
    - name: Create ~/.kube folder
      ansible.builtin.file:
        path: ~/.kube
        state: directory

    - name: Copy local ~/.kube/token to ~/.kube folder
      ansible.builtin.copy:
        src: ~/.kube/token
        dest: '/home/{{ ansible_user }}/.kube/token'
        owner: '{{ ansible_user }}'
        mode: '0400'

    - name: Check if k3s is installed
      ansible.builtin.shell: k3s --version
      register: k3s_installed
      changed_when: false
      failed_when: false

    - name: Install k3s as worker node
      when: k3s_installed.rc != 0
      ansible.builtin.shell: >-
        curl -sfL https://get.k3s.io | sh -s - agent \
          --kubelet-arg node-status-update-frequency=5s \
          --server "https://{{ k3s_fixed_reg_addr }}:6443" \
          --token-file /home/{{ ansible_user }}/.kube/token
      args:
        warn: false
      changed_when: false

    - name: Copy kube config to ~/.kube folder
      ansible.builtin.copy:
        remote_src: true
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        mode: '0600'

    - name: Replace localhost with fixed registration address in ~/.kube/config
      ansible.builtin.replace:
        path: ~/.kube/config
        regexp: '127\.0\.0\.1'
        replace: '{{ k3s_fixed_reg_addr }}'
