########################################################################
# Extra variables:
# - k3s_master_url (string)
# - k3s_token (string)
# 
# Host inventory variables:
# - None
########################################################################
- name: Install Kubernetes Master (Redundant) Nodes
  hosts: k8s_master_redundant
  tasks:
    - name: Create ~/.kube directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory

    - name: Copy k3s-server config
      ansible.builtin.copy:
        src: ~/.kube/config
        dest: ~/.kube/config

    - name: Install k3s as (redundant) master nodes
      ansible.builtin.shell: >-
        export K3S_KUBECONFIG_MODE=644
        export INSTALL_K3S_EXEC=" --no-deploy servicelb --no-deploy traefik"
        curl -sfL https://get.k3s.io | K3S_TOKEN={{ k3s_token }} sh -s - server --server {{ k3s_master_url }}
      changed_when: false
      failed_when: false

    - name: Set KUBECONFIG environment variables
      ansible.builtin.shell: >-
        export KUBECONFIG=${HOME}/.kube/config
      changed_when: false
      failed_when: false
