########################################################################
# Extra variables:
# - None
# 
# Host inventory variables:
# - None
########################################################################
- name: Uninstall Kubernetes Worker (Remote) Nodes
  hosts: k8s_worker_remote
  tasks:
    - name: Uninstall worker nodes
      ansible.builtin.shell:
        /usr/local/bin/k3s-agent-uninstall.sh
      changed_when: false
      failed_when: false

    - name: Remove ~/.kube
      ansible.builtin.file:
        path: ~/.kube
        state: absent

    - name: Remove /etc/rancher
      ansible.builtin.file:
        path: /etc/rancher
        state: absent

    - name: Remove /var/lib/rancher
      ansible.builtin.file:
        path: /var/lib/rancher
        state: absent
