########################################################################
# Extra variables:
# - None
# 
# Host inventory variables:
# - ansible_host (builtin)
# - node_name (string)
########################################################################
- name: Install Kubernetes Master (Primary) Node
  hosts: k8s_master_primary
  tasks:
    - name: Install k3s as redundant master nodes
      ansible.builtin.shell: >-
        export K3S_KUBECONFIG_MODE=644
        export INSTALL_K3S_EXEC=" --no-deploy servicelb --no-deploy traefik"
        curl -sfL https://get.k3s.io | sh -s -
      changed_when: false
      failed_when: false

    - name: Setup node as master
      ansible.builtin.shell: >-
        k3s server
      changed_when: false
      failed_when: false

    - name: Add Kubernetes label to node
      ansible.builtin.shell: >-
        kubectl label nodes {{ node_name }} kubernetes.io/role=master
      changed_when: false
      failed_when: false

    - name: Create .kube folder in home directory
      ansible.builtin.file:
        path: ~/.kube
        state: directory

    - name: Move kubeconfig to home directory
      become: true
      ansible.builtin.shell: >-
        cat /etc/rancher/k3s/k3s.yaml | sed "s/127.0.0.1/{{ ansible_host }}/" | tee ~/.kube/config
        chmod 700 ~/.kube/config
      changed_when: false
      failed_when: false
