version: '3'

################################################
# DEFINE SERVICES
################################################
services:
  jupyter-notebook:
    image: continuumio/miniconda3:latest
    container_name: jupyter-notebook
    ports:
      - 8888:8888
    command:
      - conda install jupyter -y --quiet
      - jupyter notebook --port=8888 --notebook-dir=/opt/notebooks --ip='*' --no-browser --allow-root
    volumes:
      - '/mnt/containers/jupyter-notebook:/opt/notebooks'
    restart: unless-stopped
