version: '3'

################################################
# DEFINE SERVICES
################################################
services:
  # DNSCrypt
  dnscrypt-proxy:
    image: gists/dnscrypt-proxy:latest
    container_name: dnscrypt-proxy
    ports:
      - '5053:5353/tcp'
      - '5053:5353/udp'
    volumes:
      - '/mnt/containers/dnscrypt/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro'
    networks:
      dns_net:
        ipv4_address: '10.168.53.2'
        ipv6_address: '2001:3984:3989::10'
    restart: unless-stopped
  # Pihole
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    ports:
      - '10.162.22.100:53:53/tcp'
      - '10.162.22.100:8053:80/tcp'
      - '10.162.22.100:44353:443/tcp'
      - '10.162.22.100:53:53/udp'
      - '10.162.22.100:67:67/udp'
    volumes:
      - '/mnt/containers/pihole/dnsmasq.d:/etc/dnsmasq.d'
      - '/mnt/containers/pihole/pihole:/etc/pihole'
    networks:
      dns_net:
        ipv4_address: '10.168.53.3'
        ipv6_address: '2001:3984:3989::20'
    environment:
      PIHOLE_DNS_: '10.168.53.2#5053'
      TZ: 'Asia/Manila'
    restart: unless-stopped
    depends_on:
      - dnscrypt-proxy

################################################
# DEFINE NETWORKS
################################################
networks:
  dns_net:
    driver: bridge
    ipam:
      config:
        - subnet: '10.168.53.0/24'
          gateway: '10.168.53.1'
        - subnet: '2001:3984:3989::/64'
