################################################
# DEFINE SERVICES
#
# Environment Variables:
# - CLOUDFLARE_TUNNEL_TOKEN
# - DIR_TAILSCALE (default: ./tailscale)
# - DIR_TRAEFIK (default: ./traefik)
# - DIR_WIREGUARD (default: ./wireguard)
# - IPV4_ADDR
# - HOST_CIDR
# - HOST_GATEWAY
# - HOST_IPADDR (default: 127.0.0.1)
# - DNS_SERVER (default: 127.0.0.1)
# - NETWORK_INTERFACE (default: eth0)
# - PUID (default: 1000)
# - PGID (default: 1000)
# - TAILSCALE_OAUTH_SECRET
# - TRAEFIK_DOMAIN
# - TZ (default: Asia/Manila)
# - WIREGUARD_PEERS
################################################
services:

  # ** Traefik ***
  # Open-source reverse proxy and load balancer for HTTP and TCP-based
  # applications that is easy, dynamic and full-featured.

  traefik:
    image: traefik:v3
    container_name: traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DIR_TRAEFIK:-./traefik}/traefik.yml:/etc/traefik/traefik.yml:ro
      - ${DIR_TRAEFIK:-./traefik}/dynamic_conf:/etc/traefik/dynamic_conf:rw
      - traefik_data:/data:rw
    networks:
      gateway_net:
          ipv4_address: ${IPV4_ADDR}
      traefik_vlan: {}
    environment:
      ###
      # CloudFlare DNS provider
      CLOUDFLARE_DNS_API_TOKEN_FILE: /run/secrets/cloudflare_api_key
    secrets:
      - cloudflare_api_key
    security_opt:
      - no-new-privileges:true
    healthcheck:
        test: ["CMD-SHELL", "wget --no-cache --spider http://127.0.0.1:8080/ping || exit 1"]
        interval: 30s
        timeout: 5s
        retries: 3
        start_period: 5s
    restart: unless-stopped
    labels:
      traefik.enable: true
      # HTTP Router: Redirects all traffic to HTTPS
      #traefik.http.routers.traefik.entrypoints: web
      #traefik.http.routers.traefik.rule: Host(`traefik-dashboard.${TRAEFIK_DOMAIN}`)
      #traefik.http.routers.traefik.middlewares: restricted@file
      # HTTPS Router: Handles the Dashboard
      traefik.http.routers.traefik-secure.entrypoints: websecure
      traefik.http.routers.traefik-secure.rule: Host(`traefik-dashboard.${TRAEFIK_DOMAIN}`)
      traefik.http.routers.traefik-secure.middlewares: restricted@file
      traefik.http.routers.traefik-secure.service: api@internal
      # Global SSL certificate resolver
      traefik.http.routers.traefik-secure.tls: 'true'
      traefik.http.routers.traefik-secure.tls.certresolver: cloudflare
      traefik.http.routers.traefik-secure.tls.domains[0].main: ${TRAEFIK_DOMAIN}
      traefik.http.routers.traefik-secure.tls.domains[0].sans: "*.${TRAEFIK_DOMAIN}"

  # *** Wireguard ***
  # WireGuard® is an extremely simple yet fast and modern VPN that utilizes
  # state-of-the-art cryptography.

  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    ports:
      - "${HOST_IPADDR}:51820:51820/udp"
    volumes:
      - ${DIR_WIREGUARD:-./wireguard}:/config
      - /var/modules:/lib/modules
    networks:
      vpn_vlan: {}
    environment:
      PEERDNS: ${DNS_SERVER:-127.0.0.1}
      PEERS: ${WIREGUARD_PEERS}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      SERVERURL: ${HOST_IPADDR}
      SERVERPORT: "51820"
      TZ: ${TZ:-Asia/Manila}
    # !!! The cap_add and cap_drop options are ignored when deploying a stack in swarm mode. !!!
    # Ref: https://docs.docker.com/compose/compose-file/compose-file-v3/#cap_add-cap_drop
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    restart: unless-stopped

  # *** Tailscale ***

  # tailscale:
  #   image: tailscale/tailscale:latest
  #   container_name: tailscale
  #   volumes:
  #     - ${DIR_TAILSCALE:-./tailscale}/state:/var/lib/tailscale:rw
  #   network_mode: container:traefik
  #   environment:
  #     #TS_ACCEPT_DNS: 'true'
  #     TS_AUTHKEY: ${TAILSCALE_OAUTH_SECRET}?ephemeral=true
  #     TS_DEST_IP: '172.18.0.2'
  #     TS_ENABLE_HEALTH_CHECK: 'true'
  #     TS_EXTRA_ARGS: --advertise-tags=tag:container --accept-routes --reset
  #     TS_HOSTNAME: ts-gateway
  #     TS_ROUTES: '172.18.0.0/16'
  #     TS_STATE_DIR: /var/lib/tailscale
  #     TS_USERSPACE: 'false'
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   sysctls:
  #     net.ipv4.ip_forward: 1
  #     net.ipv6.conf.all.forwarding: 1
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   healthcheck:
  #     test: wget --no-cache --spider http://127.0.0.1:9002/healthz || exit 1
  #     start_interval: 10s
  #     interval: 5m
  #     timeout: 5s
  #     retries: 3
  #   restart: unless-stopped

  # *** Cloudflare Tunnel ***

  # cloudflared:
  #  image: cloudflare/cloudflared:latest
  #  container_name: cloudflared
  #  command:
  #    - tunnel
  #    - --no-autoupdate
  #    - run
  #    - --token
  #    - ${CLOUDFLARE_TUNNEL_TOKEN}
  #  restart: unless-stopped

################################################
# DEFINE SECRETS
################################################
secrets:

  # *** Traefik ****
  cloudflare_api_key:
    file: ${DIR_TRAEFIK:-./traefik}/cloudflare_api_key.txt

################################################
# DEFINE NETWORKS
################################################
networks:

  # *** External network ****
  gateway_net:
    name: gateway-macvlan
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:-eth0}
    ipam:
      config:
        - subnet: ${HOST_CIDR}
          gateway: ${HOST_GATEWAY}

  traefik_vlan:
    name: traefik-vlan
    external: true

  vpn_vlan:
    name: vpn-vlan
    external: true

################################################
# DEFINE VOLUMES
################################################
volumes:

  # *** Persistent storage for Traefik ***
  traefik_data:
    name: traefik-data
