version: '3'

################################################
# DEFINE SERVICES
#
# Environment Variables:
# - IPV4_ADDR
# - GRAFANA_DIR (default: ./grafana)
# - HOST_CIDR
# - HOST_GATEWAY
# - NETWORK_INTERFACE (default: eth0)
# - NGINX_DIR (default: ./nginx)
# - OMADA_HOST
# - OMADA_INSECURE (default: false)
# - OMADA_PASS
# - OMADA_SITE (default: Default)
# - OMADA_USER
# - PROMETHEUS_DIR (default: ./prometheus)
################################################
services:

  # *** nginx ***
  # Reverse proxy to redirect HTTP requests to specific containers where this
  # instance is part of the network.

  nginx:
    image: nginx:mainline-alpine
    container_name: http-gateway
    volumes:
      - ${NGINX_DIR:-./nginx}/logs:/etc/nginx/logs
      - ${NGINX_DIR:-./nginx}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NGINX_DIR:-./nginx}/proxy.conf:/etc/nginx/proxy.conf:ro
    networks:
      internal_net:
        ipv4_address: 10.80.0.2
      gateway_net:
        ipv4_address: ${IPV4_ADDR}
    restart: unless-stopped

  # *** Prometheus Exporter ***
  # A Prometheus exporter for Omada.

  omada_monitor:
    image: chhaley/omada_exporter:latest
    container_name: omada-monitor
    networks:
      internal_net:
        ipv4_address: 10.80.0.5
    environment:
      OMADA_HOST: ${OMADA_HOST}
      OMADA_INSECURE: ${OMADA_INSECURE:-false}
      OMADA_PASS: ${OMADA_PASS}
      OMADA_SITE: ${OMADA_SITE:-Default}
      OMADA_USER: ${OMADA_USER}
    restart: unless-stopped

  # *** Prometheus ***
  # Prometheus is an open-source systems monitoring and alerting toolkit
  # originally built at SoundCloud. Since its inception in 2012, many companies
  # and organizations have adopted Prometheus, and the project has a very
  # active developer and user community. It is now a standalone open source
  # project and maintained independently of any company. To emphasize this, and
  # to clarify the project's governance structure, Prometheus joined the Cloud
  # Native Computing Foundation in 2016 as the second hosted project, after
  # Kubernetes.
  #
  # Prometheus collects and stores its metrics as time series data, i.e.
  # metrics information is stored with the timestamp at which it was recorded,
  # alongside optional key-value pairs called labels.

  prometheus:
    image: prom/prometheus:latest
    container_name: container-monitor
    volumes:
      - ${PROMETHEUS_DIR:-./prometheus}/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      internal_net:
        ipv4_address: 10.80.0.3
    restart: unless-stopped

  # *** Grafana ***
  # Grafana is the open source analytics & monitoring solution for every
  # database.

  grafana:
    image: grafana/grafana-oss:latest
    container_name: container-dashboard
    volumes:
      - gateway_grafana_data:/var/lib/grafana
      - ${GRAFANA_DIR:-./grafana}/grafana.ini:/etc/grafana/grafana.ini
    networks:
      internal_net:
        ipv4_address: 10.80.0.4
    restart: unless-stopped

################################################
# DEFINE NETWORKS
################################################
networks:

  # *** Internal network ***
  internal_net:
    name: gateway-vlan
    driver: bridge
    ipam:
      config:
        - subnet: 10.80.0.0/24
          gateway: 10.80.0.1

  # *** External network ****
  gateway_net:
    name: gateway-macvlan
    driver: macvlan
    driver_opts:
      parent: ${NETWORK_INTERFACE:-eth0}
    ipam:
      config:
        - subnet: ${HOST_CIDR}
          gateway: ${HOST_GATEWAY}

################################################
# DEFINE VOLUMES
################################################
volumes:

  # *** Persistent storage for Grafana ***
  # For /var/lib/grafana
  gateway_grafana_data:
    name: gateway-grafana-data
