version: '3'

################################################
# DEFINE SERVICES
#
# Environment Variables:
# - DIR_AGENT (default: ./k3s-agent)
# - DIR_SERVER (default: ./k3s-server)
# - K3S_TOKEN
# - K3S_VERSION (default: latest)
################################################
services:

  # *** k3s node with server role ***

  server_1:
    image: rancher/k3s:${K3S_VERSION:-latest}
    container_name: k3s-server-1
    command: 
      - server
    ports:
      - '6443:6443/tcp'
    privileged: true
    volumes:
      - ${DIR_SERVER:-./k3s-server}:/output
    tmpfs:
      - /run
      - /var/run
    networks:
      internal_net:
        ipv4_address: 10.64.43.10
        ipv6_address: 2001:3984:3989::10
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=644
      - K3S_TOKEN=${K3S_TOKEN}
    healthcheck:
      test: kubectl get nodes | grep $$(hostname) | grep ' Ready' || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5m
    restart: unless-stopped

  # *** k3s nodes with agent role ***

  agent_1:
    image: rancher/k3s:${K3S_VERSION:-latest}
    container_name: k3s-agent-1
    command:
      - agent
    privileged: true
    volumes:
      - ${DIR_AGENT:-./k3s-agent}/kubeconfig.yaml:$HOME/.kube/config:ro
    tmpfs:
      - /run
      - /var/run
    networks:
      internal_net:
        ipv4_address: 10.64.43.11
        ipv6_address: 2001:3984:3989::11
    environment:
      - K3S_TOKEN=${K3S_TOKEN}
      - K3S_URL=https://10.64.43.10:6443
    healthcheck:
      test: kubectl get nodes | grep $$(hostname) | grep ' Ready' || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5m
    restart: unless-stopped
    depends_on:
      - server_1

  agent_2:
    image: rancher/k3s:${K3S_VERSION:-latest}
    container_name: k3s-agent-2
    command:
      - agent
    privileged: true
    volumes:
      - ${DIR_AGENT:-./k3s-agent}/kubeconfig.yaml:$HOME/.kube/config:ro
    tmpfs:
      - /run
      - /var/run
    networks:
      internal_net:
        ipv4_address: 10.64.43.12
        ipv6_address: 2001:3984:3989::12
    environment:
      - K3S_TOKEN=${K3S_TOKEN}
      - K3S_URL=https://10.64.43.10:6443
    healthcheck:
      test: kubectl get nodes | grep $$(hostname) | grep ' Ready' || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5m
    restart: unless-stopped
    depends_on:
      - server_1

  agent_3:
    image: rancher/k3s:${K3S_VERSION:-latest}
    container_name: k3s-agent-3
    command:
      - agent
    privileged: true
    volumes:
      - ${DIR_AGENT:-./k3s-agent}/kubeconfig.yaml:$HOME/.kube/config:ro
    tmpfs:
      - /run
      - /var/run
    networks:
      internal_net:
        ipv4_address: 10.64.43.13
        ipv6_address: 2001:3984:3989::13
    environment:
      - K3S_TOKEN=${K3S_TOKEN}
      - K3S_URL=https://10.64.43.10:6443
    healthcheck:
      test: kubectl get nodes | grep $$(hostname) | grep ' Ready' || exit 1
      interval: 1m
      timeout: 3s
      retries: 3
      start_period: 5m
    restart: unless-stopped
    depends_on:
      - server_1

################################################
# DEFINE NETWORKS
################################################
networks:

  # *** Internal network ***

  internal_net:
    name: k3s-vlan
    driver: bridge
    ipam:
      config:
        - subnet: 10.64.43.0/24
          gateway: 10.64.43.1
        - subnet: 2001:3984:3989::/64
