###############################################################################
# External name configuration for the service
#
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME_LOWERCASED}
  namespace: external
  labels:
    # The name of the application
    app.kubernetes.io/name: ${SERVICE_NAME_LOWERCASED}
    # The name of a higher level application this one is part of
    app.kubernetes.io/part-of: external-services
spec:
  type: ExternalName
  externalName: ${SERVICE_IP_ADDR}
  ports:
    - name: service-port
      port: ${SERVICE_PORT}
###############################################################################
# Ingress route configuration for the service
#
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ${SERVICE_NAME_LOWERCASED}
  namespace: external
  annotations:
    kubernetes.io/ingress.class: traefik-external
  labels:
    # The name of the application
    app.kubernetes.io/name: ${SERVICE_NAME_LOWERCASED}
    # The name of a higher level application this one is part of
    app.kubernetes.io/part-of: external-services
spec:
  entryPoints:
    - websecure
  tls: {}
  routes:
    - match: Host(`${SERVICE_DOMAIN}`) && PathPrefix(`${SERVICE_PATH_PREFIX}`)
      kind: Rule
      services:
        - name: ${SERVICE_NAME_LOWERCASED}
          port: service-port
