version: '3'

################################################
# DEFINE SERVICES
#
# Environment Variables:
# - DIR_DELUGE (default: ./deluge)
# - DIR_LIDARR (default: ./lidarr)
# - DIR_MEDIA (default: /mnt/media)
# - DIR_PROWLARR (default: ./prowlarr)
# - DIR_RADARR (default: ./radarr)
# - DIR_SONARR (default: ./sonarr)
# - LAN_NETWORK (default: 192.168.1.0/24)
# - NAME_SERVERS (default: 192.168.1.1)
# - PUID (default: 1000)
# - PGID (default: 1000)
# - UMASK (default: 000)
# - VPN_CLIENT (default: wireguard)
# - VPN_INPUT_PORTS
# - VPN_OUTPUT_PORTS
# - VPN_PASS
# - VPN_PROV (default: custom)
# - VPN_USER
################################################
services:

  # *** Deluge VPN (custom image) ***
  # Deluge is a full-featured ​BitTorrent client for Linux, OS X, Unix and
  # Windows.

  # This Docker includes OpenVPN and WireGuard to ensure a secure and private
  # connection to the Internet, including use of iptables to prevent IP leakage
  # when the tunnel is down. It also includes Privoxy to allow unfiltered access
  # to index sites, to use Privoxy please point your application at 
  # http://<host ip>:8118.

  deluge-vpn:
    image: binhex/arch-delugevpn:latest
    container_name: deluge-vpn
    ports:
      - '8112:8112/tcp' # Deluge WebUI
      - '8118:8118/tcp' # Privoxy
      - '58846:58846/tcp' # Deluge Daemon
    volumes:
      - ${DIR_DELUGE:-./deluge}/data:/data
      - ${DIR_DELUGE:-./deluge}/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      DEBUG: false # Options: true|false
      DELUGE_DAEMON_LOG_LEVEL: error # Options: info|warning|error|none|debug|trace|garbage
      DELUGE_WEB_LOG_LEVEL: error # Options: info|warning|error|none|debug|trace|garbage
      ENABLE_PRIVOXY: yes # Options: yes|no
      LAN_NETWORK: ${LAN_NETWORK:-192.168.1.0/24}
      NAME_SERVERS: ${NAME_SERVERS:-192.168.1.1}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      STRICT_PORT_FORWARD: yes # Options: yes|no
      UMASK: ${UMASK:-000}
      VPN_ENABLED: yes # Options: yes|no
      VPN_USER: ${VPN_USER}
      VPN_PASS: ${VPN_PASS}
      VPN_PROV: ${VPN_PROV:-custom} # Options: pia|airvpn|custom
      VPN_CLIENT: ${VPN_CLIENT:-wireguard} # Options: openvpn|wireguard
      VPN_INPUT_PORTS: ${VPN_INPUT_PORTS}
      VPN_OUTPUT_PORTS: ${VPN_OUTPUT_PORTS}
    privileged: true
    sysctls:
      net.ipv4.conf.all.src_valid_mark: 1
    restart: unless-stopped

  # *** Lidarr ***
  # Lidarr is a music collection manager for Usenet and BitTorrent users.
  # It can monitor multiple RSS feeds for new tracks from your favorite
  # artists and will grab, sort and rename them. It can also be configured
  # to automatically upgrade the quality of files already downloaded when
  # a better quality format becomes available.

  lidarr:
    image: binhex/arch-lidarr:latest
    container_name: deluge-lidarr
    ports:
      - '8686:8686/tcp'
    volumes:
      - ${DIR_MEDIA:-./mnt/media}:/media
      - ${DIR_LIDARR:-./lidarr}/data:/data
      - ${DIR_LIDARR:-./lidarr}/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  # *** Sonarr ***
  # Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS
  # feeds for new episodes of your favorite shows and will grab, sort and rename
  # them. It can also be configured to automatically upgrade the quality of files
  # already downloaded when a better quality format becomes available.

  sonarr:
    image: binhex/arch-sonarr:latest
    container_name: deluge-sonarr
    ports:
      - '8989:8989/tcp'
      - '9897:9897/tcp'
    volumes:
      - ${DIR_MEDIA:-./mnt/media}:/media
      - ${DIR_SONARR:-./sonarr}/data:/data
      - ${DIR_SONARR:-./sonarr}/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  # *** Radarr ***
  # This fork of Sonarr aims to turn it into something like Couchpotato.

  radarr:
    image: binhex/arch-radarr:latest
    container_name: deluge-radarr
    ports:
      - '7878:7878/tcp'
    volumes:
      - ${DIR_MEDIA:-./mnt/media}:/media
      - ${DIR_RADARR:-./radarr}/data:/data
      - ${DIR_RADARR:-./radarr}/config:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      UMASK: ${UMASK:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - deluge-vpn

  # *** Prowlarr ***
  # Prowlarr is a indexer manager/proxy built on the popular arr .net/reactjs
  # base stack to integrate with your various PVR apps. Prowlarr supports both
  # Torrent Trackers and Usenet Indexers. It integrates seamlessly with Sonarr,
  # Radarr, Lidarr, and Readarr offering complete management of your indexers
  # with no per app Indexer setup required (we do it all).

  prowlarr:
    image: binhex/arch-prowlarr:latest
    container_name: deluge-prowlarr
    ports:
      - '9696:9696/tcp'
    volumes:
      - ${DIR_PROWLARR:-./prowlarr}:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      UMASK: ${PGID:-000}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    restart: unless-stopped
    depends_on:
      - lidarr
      - sonarr
      - radarr
