########################################################################
# Extra variables:
# - None
# 
# Host inventory variables:
# - None
########################################################################
- name: Uninstall Visual Studio Code using APT
  tasks:
    - name: Uninstall code
      become: true
      ansible.builtin.apt:
        name: code
        state: absent

    - name: Remove Microsoft repository
      become: true
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/microsoft.list
        state: absent

    - name: Remove Microsoft official GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        keyring: /usr/share/keyrings/microsoft.asc
        state: absent

    - name: Refresh apt package index
      become: true
      ansible.builtin.apt:
        force_apt_get: yes
        update_cache: yes
        update_cache_retries: 3
        cache_valid_time: 0 # Do not rely on cache
