version: '3'

################################################
# DEFINE SERVICES
#
# Environment variables:
# - DIR_DNSCRYPT
# - HOST_CIDR
# - HOST_GATEWAY
# - HOST_IPADDR
# - NETWORK_INTERFACE (default: eth0)
# - PIHOLE_PASS
# - TIME_ZONE (default: America/Chicago)
################################################
services:

  # *** DNSCrypt ***
  # DNSCrypt is a protocol that encrypts, authenticates and optionally anonymizes
  # communications between a DNS client and a DNS resolver.

  dnscrypt-proxy:
    image: gists/dnscrypt-proxy:latest
    container_name: dns-over-https
    volumes:
      - ${DIR_DNSCRYPT}/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro
    networks:
      internal_net:
        ipv4_address: 10.53.0.2
    healthcheck:
      test: nslookup cloudflare.com 127.0.0.11 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

  # *** Pi-hole ***
  # In addition to blocking advertisements, Pi-hole has an informative Web
  # interface that shows stats on all the domains being queried on your network.

  pihole:
    image: pihole/pihole:latest
    container_name: doh-sinkhole
    ports:
      - '${HOST_IPADDR}:53:53/tcp'
      - '${HOST_IPADDR}:53:53/udp'
      - '${HOST_IPADDR}:8053:80/tcp'
    volumes:
      - doh-sinkhole_dnsmasq_data:/etc/dnsmasq.d
      - doh-sinkhole_pihole_data:/etc/pihole
    networks:
      internal_net:
        ipv4_address: 10.53.0.3
    environment:
      INTERFACE: ${NETWORK_INTERFACE:-eth0}
      PIHOLE_DNS_: 10.53.0.2#5353
      REV_SERVER: true
      REV_SERVER_CIDR: ${HOST_CIDR}
      REV_SERVER_TARGET: ${HOST_GATEWAY}
      TZ: ${TIME_ZONE:-America/Chicago}
      WEBPASSWORD: ${PIHOLE_PASS}
    healthcheck:
      test: nslookup cloudflare.com 127.0.0.11 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - dnscrypt-proxy

  # *** Prometheus Exporter ***
  # A Prometheus exporter for Pi-hole.

  prometheus:
    image: ekofr/pihole-exporter:latest
    container_name: doh-sinkhole-monitor
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    networks:
      internal_net:
        ipv4_address: 10.53.0.4
    environment:
      PIHOLE_HOSTNAME: 10.53.0.3
      PIHOLE_PASSWORD: ${PIHOLE_PASS}
      PORT: '9617'
    restart: always
    depends_on:
      - pihole

################################################
# DEFINE NETWORKS
################################################
networks:

  # *** Internal network ***
  internal_net:
    name: doh-vlan
    driver: bridge
    ipam:
      config:
        - subnet: 10.53.0.0/24
          gateway: 10.53.0.1

################################################
# DEFINE VOLUMES
################################################
volumes:

  # *** Persistent storage for Pi-hole ***
  # For /etc/dnsmasq.d
  doh-sinkhole_dnsmasq_data:
    name: doh-sinkhole-dnsmasq-data
  # For /etc/pihole 
  doh-sinkhole_pihole_data:
    name: doh-sinkhole-pihole-data
