################################################
# DEFINE SERVICES
#
# Environment variables:
# - DIR_DNSCRYPT (default: ./dnscrypt)
# - DIR_PIHOLE (default: ./pihole)
# - HOST_IPADDR
# - NETWORK_INTERFACE (default: eth0)
# - PIHOLE_PASS
# - TZ (default: America/Chicago)
################################################
services:

  # *** DNSCrypt ***
  # DNSCrypt is a protocol that encrypts, authenticates and optionally anonymizes
  # communications between a DNS client and a DNS resolver.

  dnscrypt-proxy:
    image: gists/dnscrypt-proxy:latest
    container_name: dns-over-https
    volumes:
      - ${DIR_DNSCRYPT:-./dnscrypt}/dnscrypt-proxy.toml:/etc/dnscrypt-proxy/dnscrypt-proxy.toml:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.53.0.2
    healthcheck:
      test: nslookup -port=5353 cloudflare.com 127.0.0.1 || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always

  # *** Pi-hole ***
  # In addition to blocking advertisements, Pi-hole has an informative Web
  # interface that shows stats on all the domains being queried on your network.

  pihole:
    image: pihole/pihole:latest
    container_name: doh-sinkhole
    ports:
      - '${HOST_IPADDR}:53:53/tcp'
      - '${HOST_IPADDR}:53:53/udp'
      - '${HOST_IPADDR}:8053:80/tcp'
    volumes:
      - ${DIR_PIHOLE:-./pihole}/dnsmasq.d:/etc/dnsmasq.d:rw
      - pihole_data:/etc/pihole
      - /etc/localtime:/etc/localtime:ro
    networks:
      internal_net:
        ipv4_address: 10.53.0.3
      traefik_vlan: {}
    environment:
      FTLCONF_dns_interface: ${NETWORK_INTERFACE:-eth0}
      FTLCONF_dns_upstreams: 10.53.0.2#5353
      FTLCONF_misc_etc_dnsmasq_d: "true"
      FTLCONF_webserver_api_password: ${PIHOLE_PASS}
      TZ: ${TZ:-America/Chicago}
    cap_add:
      # FTL needs to be able to set the system time to update it using the
      # Network Time Protocol (NTP) in the background.
      - SYS_TIME
    healthcheck:
      test: nslookup -port=5353 cloudflare.com 10.53.0.2 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    depends_on:
      - dnscrypt-proxy

################################################
# DEFINE NETWORKS
################################################
networks:

  # *** Internal network ***
  internal_net:
    name: doh-vlan
    driver: bridge
    ipam:
      config:
        - subnet: 10.53.0.0/24
          gateway: 10.53.0.1

  # *** External network ****
  traefik_vlan:
    name: traefik-vlan
    external: true

################################################
# DEFINE VOLUMES
################################################
volumes:

  # *** Persistent storage for Pi-hole ***
  # For /etc/pihole
  pihole_data:
    name: pihole-data
